language: python
python:
  - "3.8"
services:
  - docker
# command to install dependencies
install:
  - docker-compose build
  - pip install coveralls
# command to run tests
script:
  - docker-compose run -e --no-deps --rm search coverage run manage.py test
  - coveralls
