version: '3'

services:
  search:
    image: search
    build: .
    ports:
      - 8000:8000
    environment:
      - API_KEY=${API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
